### ISSUE TITLE
can not be installed on Android 11

### ISSUE THREAD

**Issue by yinx2002** [Xposed-Modules-Repo/com.ztc1997.fakedcbacklight#1]
can not be installed on Android 11

**Comment by yinx2002** [comment]
Why closed? Without any comment ? The apk downloaded just can not be interpreted.

**Comment by ztc1997** [comment]
There are no plans to support old systems, or you can submit a pr.

**Comment by yinx2002** [comment]
Android 11 is already old? If it really does to your project , please label it somewhere instead of closing the issue without any explanation, or even add it in comment, I will see it.  In case of the information was added anywhere I will not ask that question.
